### ISSUE TITLE
Can't mock class Chatwork

### ISSUE THREAD

**Issue by quanghung97** [sun-asterisk-research/chatwork-php#19]
here my code
```php
$chatwork = Chatwork::withAPIToken('some-key');
```

when I use mock and test
```php
$mock = Mockery::mock('alias:SunAsterisk\Chatwork\Chatwork');

$mock->shouldReceive('withAPIToken')->once();
```

```
Mockery\Exception\InvalidCountException: Method withAPIToken(<Any Arguments>) from SunAsterisk\Chatwork\Chatwork should be called
 exactly 1 times but called 0 times.
```

**Comment by oliverquynh** [comment]
Hope these links can help you!
http://docs.mockery.io/en/latest/reference/public_static_properties.html
https://stackoverflow.com/questions/35910961/phpuse-mockery-to-mock-a-static-method-called-in-another-static-method

**Comment by quanghung97** [comment]
@xuanquynh
If this method WithAPIToken return Object, String, anythings... I can mock with alias but 
withAPIToken() call another static APIToken(). I can't use alias to solve this problem.

```
public static function withAPIToken(string $token)
    {
        return new static(new APIToken($token));
    }
```

https://stackoverflow.com/questions/35910961/phpuse-mockery-to-mock-a-static-method-called-in-another-static-method

> Note that class can't be loaded yet. Otherwise mockery won't be able to alias it.

Can you fix this problem ?

**Comment by oliverquynh** [comment]
What is the test case that you want to test here?

**Comment by quanghung97** [comment]
```php
public function sendMessages($messages)
    {
        $bot = $this->webhook->bot;
        $roomId = $this->webhook->room_id;
        $chatwork = Chatwork::withAPIToken($bot->bot_key);

        foreach ($messages as $key => $message) {
            try {
                $chatwork->room($roomId)->messages()->create($message);
                array_splice($messages, $key, 1);
                // save success message_history
                $this->saveMessageHistory($message, MessageHistoryStatus::SUCCESS);
            } catch (APIException $error) {
                switch ($error->getStatus()) {
                    case 403:
                        // permission denined
                        $this->saveMessageHistory($message, MessageHistoryStatus::FAILED, 'Permission');
                        break 2;
                    case 429:
                        // limit request
                        // add to queue and excute this job after 5 minutes
                        SendMessageToChatwork::dispatch($bot, $roomId, $messages, $this->payloadHistory->id)
                            ->onQueue('high')
                            ->delay(now()->addMinutes(5));
                        break 2;
                    case 401:
                        // authorized
                        $this->saveMessageHistory($message, MessageHistoryStatus::FAILED, 'Unauthorized');
                        break 2;
                    default:
                        // handle timeout error
                }
            }
        }
    }
```
I want test this function, this case always throw APIException code 401 when i fake $bot->bot_key. I dont want use real data, i just want throw another code with mock ` Chatwork::withAPIToken($bot->bot_key);`

**Comment by oliverquynh** [comment]
You shouldn't use `$chatwork = Chatwork::withAPIToken($bot->bot_key);` inside this function. You have to use dependency injection or you can't apply unit test for any code. Inject a mock instance of Chatwork and mock $chatwork->room($roomId)->messages()->create($message) throws your expected exceptions.

**Comment by quanghung97** [comment]
how to mock `$chatwork->room($roomId)->messages()->create($message);`

**Comment by oliverquynh** [comment]
"Talk is cheap. Show me the code." I can't explain more by talk. I give you a code example. Hope it will help.

Access code inside this branch https://github.com/xuanquynh/chatwork-php/tree/support-quanghung97

**Comment by ghost** [comment]
@xuanquynh thank you xuanquynh. i was resolved issue. As you suggested, i did using inject dependency chatwork class and mock this class such as i want instead of initizlize them inside service.

**Comment by quanghung97** [comment]
Thank you @xuanquynh .
